### ISSUE TITLE
Remover chave pública do index.html

### ISSUE THREAD

**Issue by falehenrique** [goblockchain/DApp#5]
Remover endereço fixo de owner da index.html

O responsável por adicionar os Autorizadores é a conta **0x71c20da180d9d50bdfeac773942636d1695b9ec0** O responsável poderá ser alterado mediante votação no Aragon .

**Comment by lucibati** [comment]
Alterações realizadas. 

Incluídos no repositório os arquivos Main.js e Index.html alterados.

**Comment by esdrasedu** [comment]
Vi muito `addresses` sendo usado hard code na **GoBlockchain**, vcs já pensando em usar o ENS para resolver isso, usando os subdominios para cada contrato?
